openapi: 3.0.0
info:
  title: RECO API
  version: 1.0.0
  description: API for RECO's accaunts

servers:
 - url: /api

components:
  schemas:
    Person:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
        user_id:
          type: string
        name:
          type: string
        surname:
          type: string
  parameters:
    user_id:
      name: user_id
      in: path
      required: true
      schema:
        type: string

paths:
  /people:
    get:
      summary: Get lisf of all people
      tags:
        - People
      operationId: people.get_all_people
      responses:
        '200':
          description: Successfully read all people
    post:
      summary: Create a new person 
      tags:
        - People
      operationId: people.create_person
      requestBody:
        description: Person to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201': 
          description: Successfully created a new person
  
  /people/{user_id}:
    get:
      summary: Get a person by user id
      tags:
        - People
      operationId: people.get_person
      description: Get a person by user id
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: Successfully read a person
    put:
      summary: Update a person by user id
      tags:
        - People
      operationId: people.update_person
      parameters:
        - $ref: '#/components/parameters/user_id'
      requestBody:
        description: Person to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: Successfully updated a person
    delete:
      summary: Delete a person by user id
      tags:
        - People
      operationId: people.delete_person
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '204':
          description: Successfully deleted a person